// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:2e2e43b6-d972-4d8d-8096-9550c43fb033',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awsleaf-hosting-mobilehub-692196837',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1v1v2exxk92i9.cloudfront.net',
    'aws_mobile_analytics_app_id': '1de5d31d26d5435d8e945b557616e237',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '0f617b4f-466c-4be9-bc97-b1c06a43bf6e',
    'aws_project_name': 'AWSLeaf',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'awsleaf-mobilehub-692196837',
}

export default awsmobile;
